trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.create, name="create"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('routes/', views.routes, name="routes"),
    path('daily/<str:day>', views.daily, name="daily"),
    path('serviced/<int:customer_id>/', views.serviced, name="serviced"),
    # path('choose_route/', views.choose_route, name="choose_route"),
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding Django's built in routes (login and logout). Notice there is no 'login' function in accounts/views.py. Django takes care of this for us.
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate trach_collector/views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/employees/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    zip_code = models.CharField(max_length=5)

    def __str__(self):
        return self.name

trash_collector/employees/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.http.request import QueryDict
from django.shortcuts import render
from django.apps import apps
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from datetime import date
from .models import Employee
import calendar

# Create your views here.

# TODO: Create a function for each path created in employees/urls.py. Each will need a template as well.

@login_required
def index(request):
    # This line will get the Customer model from the other app, it can now be used to query the db for Customers
    Customer = apps.get_model('customers.Customer')
    logged_in_user = request.user

    try:
        today_date = date.today()
        today_day = calendar.day_name[today_date.weekday()]
        logged_in_employee = Employee.objects.get(user=logged_in_user)
        customers_in_zip = Customer.objects.filter(zip_code = logged_in_employee.zip_code)
        pickup_today = customers_in_zip.filter(weekly_pickup = today_day) | customers_in_zip.filter(one_time_pickup = today_date)
        non_suspended = pickup_today.exclude(suspend_start__lt = today_date, suspend_end__gt = today_date)
        customers_not_picked_up = non_suspended.exclude(date_of_last_pickup = today_date)
        
        context = {
            'logged_in_employee': logged_in_employee,
            'today_date': today_date,
            'today_day' : today_day,
            'customers_not_picked_up': customers_not_picked_up
        }
        return render(request, 'employees/index.html', context)
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('employees:create'))

@login_required
def create(request):
    logged_in_user = request.user
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        zip_from_form = request.POST.get('zip_code')
        new_employee = Employee(name=name_from_form, user=logged_in_user, zip_code=zip_from_form)
        new_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        return render(request, 'employees/create.html')

def edit_profile(request):
    logged_in_user = request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    if request.method == "POST":
        name_from_form = request.POST.get('name')
        zip_from_form = request.POST.get('zip_code')
        logged_in_employee.name = name_from_form
        logged_in_employee.zip_code = zip_from_form
        logged_in_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        context = {
            'logged_in_employee': logged_in_employee
        }
        return render(request, 'employees/edit_profile.html', context)

def serviced(request,customer_id):
    logged_in_user = request.user

    Customer = apps.get_model('customers.Customer')
    customer_info = Customer.objects.get(pk = customer_id)
    curr_date = date.today()
        
    if customer_info.date_of_last_pickup != curr_date:
        customer_info.date_of_last_pickup= curr_date
        customer_info.balance += 20
        customer_info.save()

    return HttpResponseRedirect(reverse('employees:index'))


def routes(request):
    logged_in_user = request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    Customer = apps.get_model('customers.Customer')
    customers = Customer.objects.filter(zip_code = logged_in_employee.zip_code)
    context = {
        'logged_in_employee':logged_in_employee,
        'customers' : customers
    }

    return render(request, 'employees/routes.html', context)

def daily(request, day):
    logged_in_user = request.user
    logged_in_employee = Employee.objects.get(user=logged_in_user)
    Customer = apps.get_model('customers.Customer')
    customers_in_zip = Customer.objects.filter(zip_code = logged_in_employee.zip_code)
    customers = customers_in_zip.filter(weekly_pickup = day)

    context = {
        'logged_in_employee':logged_in_employee,
        'customers' : customers,
        'day' : day
    }

    return render(request, 'employees/routes.html', context)

trash_collector/employees/templates/employees/create.html
{% extends 'base.html' %}

{% block title %} Employee Create {% endblock %}

{% block header %} Please Complete Registration {% endblock %}

{% block content %}

<form action="{% url 'employees:create' %}" method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" id="name"><br />
    Zip Code: <input type="text" name="zip_code" id="zip_code"><br />
    <input type="submit" value="Register">
</form>

{% endblock %}

trash_collector/employees/templates/employees/edit_profile.html
{% extends 'employees/employee_base.html' %}
{% block title %} Employee Profile Edit {% endblock %}
{% block header %} Update Your Information {% endblock %} 
{% block content %}

<br>
<div class = "container">
    <form class = "form-horizontal" action = "{% url 'employees:edit_profile' %}" method = "post">
        {% csrf_token%}
        <div class = "form-group">
            <label align = "left" class = "col-2" for = 'name'>Name:</label>
            <input align = "left" type = "text" class = "col-6" name = "name" id = "name" value = "{{logged_in_employee_name}}">

        </div> <br>

        <div class="form-group"> 
            <label align ="left" class = "col-2" for ='zip_code'>Zip Code:</label> 
            <input align ="left"  type="text"class = "col-6" name="zip_code" id="zip_code" value="{{logged_in_employee.zip_code}}">
            
        </div> <br>

        <div class="form-group"> 
            <div class = "col-md-4">
                <br> 
            <input class="btn btn-primary" type="submit" value="Submit">
        
        </div> <br>
    </div>
    
    </form>
    
    
    
</div> 

{% endblock %}

trash_collector/employees/templates/employees/employee_base.html
{% extends 'base.html' %}

{% block navbar %}
    <a class="nav-item nav-link" href="{% url 'employees:index' %}">Home</a>
    <a class="nav-item nav-link" href="{% url 'employees:routes' %}">Routes</a>
    <a class="nav-item nav-link" href="{% url 'employees:edit_profile' %}">Edit Profile</a>
{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'employees/employee_base.html' %} 

{% block title %}{% block header %} Employee Home {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello {{ logged_in_employee.name }}! Today is {{ today_day }}, {{ today_date }}. These customers are awaiting pickup: 
    <ul class="list-group">
    {% for customer in customers_not_picked_up %}
      <li class="list-group-item">{{customer.name}} - {{customer.address}}    <a class="btn btn-success btn-sm" href="{% url 'employees:serviced' customer.id %}" role="button">Complete</a> </li> 
    {% endfor %}
    </ul>
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/employees/templates/employees/routes.html
{% extends 'employees/employee_base.html' %}

{% block title %}{% block header %} {{logged_in_employee}}'s {{ day }} Routes {% endblock %}{% endblock %}

{% block content %}

<a href="{% url 'employees:daily' 'Monday' %}">Monday</a> | 
<a href="{% url 'employees:daily' 'Tuesday' %}">Tuesday</a> | 
<a href="{% url 'employees:daily' 'Wednesday' %}">Wednesday</a> | 
<a href="{% url 'employees:daily' 'Thursday' %}">Thursday</a> | 
<a href="{% url 'employees:daily' 'Friday' %}">Friday</a> | 
<br>
<br>
    <ul class="list-group">
    {% for customer in customers %}
      <li class="list-group-item">{{customer.name}} - {{customer.address}}</li>  
    {% endfor %}
    </ul>


{% endblock %}